### ISSUE TITLE
Bottom Overflowed

### ISSUE THREAD

**Issue by mue-barakat** [rajayogan/flutter-minimalloginUI#1]
When using the provided main.dart, i get bottom overflow on my S7 Edge

**Comment by rajayogan** [comment]
Well, 2 ways to fix it.. 

1) Adjust the positioned widget in such a way that it fits the screen.. (Not recommended)

2) Wrap the entire body inside a ListView.. (If you notice I am using a Column in the main.dart and columns don't come with scroll). After wrapping remove the resizeToAvoidBottomPadding: false line in the scaffold.

(I was planning to do this myself and push in a commit, but got caught up in other work and videos. Sorry)
